# Generated by Django 5.2.5 on 2025-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="street",
            new_name="company_name",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="fh"),
            preserve_default=False,
        ),
    ]
