# Generated by Django 5.2.5 on 2025-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_street_user_company_name_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
