# Generated by Django 5.2.5 on 2025-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_info_completed',
            field=models.BooleanField(default=False),
        ),
    ]
