# Generated by Django 5.2.5 on 2025-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_business_info_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_phone_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
