# Generated by Django 5.2.5 on 2025-08-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_account_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="applications_submitted_this_week",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="contracts_scanned_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="hours_saved_this_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="potential_matches_identified",
            field=models.IntegerField(default=0),
        ),
    ]
