# Generated by Django 5.2.5 on 2025-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_applications_submitted_this_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_stage',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('PAID', 'PAID'), ('QUESTIONS', 'QUESTIONS'), ('DASHBOARD', 'DASHBOARD')], default='REGISTERED', help_text='Current registeration stage', max_length=20),
        ),
    ]
