# Generated by Django 5.2.5 on 2025-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_ref_code_user_signup_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_stage',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('PAID', 'PAID'), ('ANSWERED', 'ANSWERED'), ('DASHBOARD', 'DASHBOARD')], default='REGISTERED', help_text='Current registeration stage', max_length=20),
        ),
    ]
