# Generated by Django 5.2.5 on 2025-09-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_payment_confirmed_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_id',
        ),
    ]
