# Generated by Django 5.2.5 on 2025-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_invoice_amount_alter_invoice_planname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="industry_type",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
