# Generated by Django 5.2.5 on 2025-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('USER', 'USER'), ('INDUSTRY', 'INDUSTRY')], default='USER', max_length=10),
        ),
    ]
