# Generated by Django 5.2.5 on 2025-12-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_business_name_user_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='applications_submitted_this_week',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_info_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companyRepID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contracts_scanned_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hours_saved_this_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_business_registered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_payment_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='planName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='potential_matches_identified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signup_stage',
        ),
    ]
