# Generated by Django 5.2.5 on 2026-02-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_account_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountquestions',
            name='user',
        ),
        migrations.AddField(
            model_name='accountquestions',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
