# Generated by Django 5.2.5 on 2026-02-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_accountquestions_user_accountquestions_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountquestions',
            name='email',
            field=models.EmailField(blank=True, default='defaultemail@gmail.com', max_length=254),
        ),
    ]
