# Generated by Django 5.2.5 on 2026-02-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_accountquestions_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_book_session_payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
