# Generated by Django 5.2.5 on 2026-02-14 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_is_book_session_payment_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountquestions",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
