# Generated by Django 6.0.5 on 2026-05-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_accountquestions_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachdetail",
            name="user",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
        migrations.DeleteModel(
            name="AccountQuestions",
        ),
        migrations.DeleteModel(
            name="CoachDetail",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
