# Generated by Django 5.2.5 on 2026-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_remove_coachdetail_user_remove_invoice_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="safe_word",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
