# Generated by Django 5.2.5 on 2026-08-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_safe_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_auth',
            field=models.BooleanField(default=False),
        ),
    ]
