# Generated by Django 5.2.5 on 2026-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_google_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
