# Generated by Django 5.2.5 on 2026-10-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_notification_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
