# Generated by Django 5.2.5 on 2026-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelocation',
            name='arrived_home_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelocation',
            name='is_home',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homelocation',
            name='left_home_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
