# Generated by Django 5.2.5 on 2026-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelocations', '0002_homelocation_arrived_home_at_homelocation_is_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelocation',
            name='is_home',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
