# Generated by Django 6.0.5 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="image",
            field=models.FileField(upload_to="memories/"),
        ),
    ]
