# Generated by Django 6.0.5 on 2026-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_alter_memory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="image",
            field=models.ImageField(upload_to="memories/"),
        ),
    ]
