# Generated by Django 6.0.5 on 2026-06-09 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LockedDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("now", "Now"), ("scheduled", "Scheduled")],
                        default="now",
                        max_length=10,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("starting_point_name", models.CharField(max_length=700)),
                ("destination_name", models.CharField(max_length=700)),
                ("starting_coords", models.JSONField()),
                ("ending_coords", models.JSONField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "date_time_started",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
