# Generated by Django 6.0.5 on 2026-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockeddestinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockeddestination",
            name="destination_address_name",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
