# Generated by Django 5.2.5 on 2026-09-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockeddestinations', '0002_lockeddestination_destination_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockeddestination',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockeddestination',
            name='drifted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockeddestination',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lockeddestination',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
