# Generated by Django 5.2.5 on 2026-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockeddestinations', '0003_lockeddestination_arrived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockeddestination',
            name='expected_return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
