# Generated by Django 5.2.5 on 2026-09-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockeddestinations', '0004_lockeddestination_expected_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockeddestination',
            name='checkin_task_ids',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='lockeddestination',
            name='notification_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
